version: '2'

services:
  postgres:
    image: postgres:13.4-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
