version: '2'

services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: kiavash
      POSTGRES_PASSWORD: password
      POSTGRES_DB: focusedai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
