name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: circleci/postgres:13.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: focusedai
          POSTGRES_USER: kiavash
          POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          sleep 10  # Allow some time for the database to start properly
      
      - name: Setup database
        run: |
          if ! psql -h localhost -U kiavash -lqt | cut -d \| -f 1 | grep -qw focusedai; then
            psql -h localhost -U kiavash -d postgres -c 'CREATE DATABASE focusedai'
          else
            echo "Database focusedai already exists."
          fi
        env:
          PGPASSWORD: password
        

      - name: Run tests
        run: |
          pytest ./test/test_main.py