name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: focusedai
          POSTGRES_USER: kiavash
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Setup database
        run: |
          psql -h postgres -U kiavash -c 'CREATE DATABASE "focusedai";'
        env:
          PGPASSWORD: password

      - name: Run tests
        run: |
          pytest ./test/test_main.py
